apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ark-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 88.184.158.243/32  # â† Ton IP publique

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ark-l2
  namespace: metallb-system
spec: {}
